inherit_from:
  - https://raw.githubusercontent.com/apartmentlist/style/master/.rubocop-global.yml

AllCops:
  # Ruby files that are otherwise missed, since default is just *.rb
  Include:
    - config.ru
    - Gemfile
    - Rakefile
  # Files that aren't helpful to check, even if they're Ruby
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
